// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFidvhAhgvb4GKmpUSSsGbkvO3cmDeyEg',
    appId: '1:722983022196:web:665c5e4d0ec3e61053ab21',
    messagingSenderId: '722983022196',
    databaseURL: "https://porfolio-336218-default-rtdb.firebaseio.com",
    projectId: 'porfolio-336218',
    authDomain: 'porfolio-336218.firebaseapp.com',
    storageBucket: 'porfolio-336218.appspot.com',
    measurementId: 'G-W128YWZFJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg05u4rf5M3OsxfoOZcs1AIDifKhziFSM',
    appId: '1:722983022196:android:5a39dc5d213812fe53ab21',
    messagingSenderId: '722983022196',
    projectId: 'porfolio-336218',
    storageBucket: 'porfolio-336218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GLO34cdPFwGtbHIN0F0I2W2SMbL7OAI',
    appId: '1:722983022196:ios:12386d1f54c5abaf53ab21',
    messagingSenderId: '722983022196',
    projectId: 'porfolio-336218',
    storageBucket: 'porfolio-336218.appspot.com',
    iosClientId: '722983022196-71pnoro4c0io3cv3sgtnrh2r8f913dug.apps.googleusercontent.com',
    iosBundleId: 'com.devexpert.portfolio',
  );
}
